project/cliente/urls.py
from django.urls import  path
from .views import index

app_name = "cliente"


urlpatterns = [
    path("", index, name="index"),   
]

project/config/urls.py
from django.contrib import admin
from django.urls import include, path
#from .views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    #path("", index, name="index"),
    path("cliente/", include("cliente.urls", "cliente")),
    #path("producto/", include("producto.urls", "producto")),
]

project/producto/urls.py
#from django.urls import include, path
#from .views import index

#app_name = "producto"

#urlpatterns = [
#    path("", index, name="index"),
#    path("producto/", include("producto.urls", "producto")),
#]
from django.contrib.admin.views.decorators import staff_member_required
from django.urls import path
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    path("", TemplateView.as_view(template_name="producto/index.html"), name="index"),
    path("productocategoria/detail/<int:pk>", views.ProductoCategoriaDetail.as_view(), name="productocategoria_detail"),
    path("productocategoria/list/", views.ProductoCategoriaList.as_view(), name="productocategoria_list"),
    path("productocategoria/create/", staff_member_required(views.ProductoCategoriaCreate.as_view()), name="productocategoria_create"),
    path("productocategoria/delete/<int:pk>", staff_member_required(views.ProductoCategoriaDelete.as_view()), name="productocategoria_delete"),
    path("productocategoria/update/<int:pk>", staff_member_required(views.ProductoCategoriaUpdate.as_view()), name="productocategoria_update"),
    path("producto/create/", views.ProductoCreate.as_view(), name="producto_create"),
    path("producto/list/", views.ProductoList.as_view(), name="producto_list"),
    path("producto/detail/<int:pk>", views.ProductoDetail.as_view(), name="producto_detail"),
    path("producto/delete/<int:pk>", views.ProductoDelete.as_view(), name="producto_delete"),
    path("producto/update/<int:pk>", views.ProductoUpdate.as_view(), name="producto_update"),
]

project/cliente/models.py
from django.db import models

class Pais(models.Model):
    nombre = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.nombre
    
class Cliente(models.Model):
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    pais_origen_id = models.ForeignKey(Pais, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f"{self.nombre} {self.apellido}"

project/producto/models.py
#from django.db import models

#class Producto(models.Model):
#    descripcion = models.CharField(max_length=50)

#   def __str__(self):
#        return self.descripcion
from django.db import models
from django.utils import timezone


class ProductoCategoria(models.Model):
    """Categorías de productos."""

    nombre = models.CharField(max_length=100, unique=True)
    descripcion = models.CharField(max_length=250, null=True, blank=True, verbose_name="descripción")

    class Meta:
        verbose_name = "categoría de productos"
        verbose_name_plural = "categorías de productos"

    def __str__(self):
        """Representa una instancia de la clase como una cadena de texto."""
        return self.nombre


class Producto(models.Model):
    """Productos que corresponden a una categoría. Cada vez que se actualiza el precio, se modifica la fecha de actualización."""

    categoria = models.ForeignKey(ProductoCategoria, on_delete=models.SET_NULL, blank=True, null=True, verbose_name="categoría")
    nombre = models.CharField(max_length=100)
    unidad_de_medida = models.CharField(max_length=50)
    cantidad = models.FloatField()
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    descripcion = models.CharField(max_length=250, blank=True, null=True, verbose_name="descripción")
    fecha_actualizacion = models.DateTimeField(default=timezone.now, editable=False, verbose_name="fecha de actualización")

    class Meta:
        verbose_name = "producto"
        verbose_name_plural = "productos"

    def __str__(self) -> str:
        return f"{self.nombre} ({self.unidad_de_medida}) ${self.precio:.2f}"

project/producto/forms.py
from django import forms

from . import models


class ProductoCategoriaForm(forms.ModelForm):
    class Meta:
        model = models.ProductoCategoria
        fields = "__all__"

        widgets = {
            "nombre": forms.TextInput(attrs={"class": "form-control"}),
            "descripcion": forms.TextInput(attrs={"class": "form-control"}),
        }


class ProductoForm(forms.ModelForm):
    class Meta:
        model = models.Producto
        fields = "__all__"

project/cliente/views.py
from django.shortcuts import render
from .models import Cliente

def index(request):
    clientes = Cliente.objects.all()
    datos = {"clientes": clientes}
    return render(request, "cliente/index_cliente.html", datos)

project/config/views.py
from django.shortcuts import render 


def index(request):
    return render(request, "index.html")

project/producto/views.py
#from django.shortcuts import render
#from .models import Producto

#def index(request):
    #productos = Producto.objects.all()
#    return render(request, "producto/index_producto.html")
#from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

#from project.apps.producto import mis_modelos_nuevos

from . import forms, models

# ***** Categoría de Productos
# *****************************


class ProductoCategoriaDetail(DetailView):
    model = models.ProductoCategoria


class ProductoCategoriaList(ListView):
    model = models.ProductoCategoria

    def get_queryset(self):
        if self.request.GET.get("consulta"):
            query = self.request.GET.get("consulta")
            object_list = models.ProductoCategoria.objects.filter(nombre__icontains=query)
        else:
            object_list = models.ProductoCategoria.objects.all()
        return object_list


class ProductoCategoriaCreate(CreateView):
    model = models.ProductoCategoria
    form_class = forms.ProductoCategoriaForm
    success_url = reverse_lazy("producto:index")


class ProductoCategoriaDelete(DeleteView):
    model = models.ProductoCategoria
    success_url = reverse_lazy("producto:productocategoria_list")


class ProductoCategoriaUpdate(UpdateView):
    model = models.ProductoCategoria
    success_url = reverse_lazy("producto:productocategoria_list")
    form_class = forms.ProductoCategoriaForm


# ***** Producto
# *****************************


class ProductoCreate(CreateView):
    model = models.Producto
    form_class = forms.ProductoForm
    success_url = reverse_lazy("producto:index")


class ProductoList(ListView):
    model = models.Producto


class ProductoDetail(DetailView):
    model = models.Producto


class ProductoDelete(DeleteView):
    model = models.Producto
    success_url = reverse_lazy("producto:producto_list")


class ProductoUpdate(UpdateView):
    model = models.Producto
    success_url = reverse_lazy("producto:producto_list")
    form_class = forms.ProductoForm

project/cliente/templates/cliente/index_cliente.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1> CLIENTES </h1>
    {% for cliente in clientes %}
    <h2>{{cliente.nombre}}</h2>
    <p>{{cliente.apellido}}</p>
    <p>{{cliente.pais_origen_id}}</p>    
    {% endfor %}  

    <a href="{% url 'index' %}">Volver al Menu Principal</a>
</body>
</html>

project/producto/templates/producto/index_back.html
<a href="{% url 'producto:index' %}" class="btn btn-info">Volver a índice de Producto</a>

project/producto/templates/producto/index_producto.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

{% extends 'home/base.html' %}


{% block content %}

    <h1 class="shadow-lg text-center">App Producto</h1>
    <div class="container mt-lg-3">

      

        {% block content_producto %}
            <h3 class="pb-lg-3">
                Categorías de Productos
            </h3>

            <div class="d-grid gap-3">
                {% if user.is_staff %}
                    <a href="{% url 'producto:productocategoria_create' %}" class="btn btn-primary">Crear</a>
                {% endif %}
                <a href="{% url 'producto:productocategoria_list' %}" class="btn btn-primary">Listar</a> <br>
            </div>

            <h3 class="pb-lg-3">
                Productos
            </h3>

            <div class="d-grid gap-3">
                {% if user.is_staff %}
                    <a href="{% url 'producto:producto_create' %}" class="btn btn-primary">Crear</a>
                {% endif %}
                <a href="{% url 'producto:producto_list' %}" class="btn btn-primary">Listar</a> <br>
            </div>

        {% endblock content_producto %}

    </div>
{% endblock content %}

project/producto/templates/producto/prodcateg_confirm_delete.html
{% extends 'producto/index.html' %}


{% block title %} Eliminación de Categoría de Productos {% endblock title %}

{% block content_producto %}

    <p class="fs-5 fst-italic ">¿Confirmas eliminar "{{ object }}"?</p>

    <form method="post">
        {% csrf_token %}
        <div class="d-grid gap-3">
            <button type="submit" class="btn btn-danger">Confirmar</button>
            {% include 'producto/index_back.html' %}
        </div>
    </form>


{% endblock content_producto %}

project/producto/templates/producto/prodcateg_detail.html
{% extends 'producto/index.html' %}


{% block title %} Detalle de Categorías de Productos {% endblock title %}

{% block content_producto %}

    <ul>
        <li>
            <p><strong>Nombre:</strong> {{ object.nombre }}</p>
            <p><strong>Detalle:</strong> {{ object.descripcion }}</p>
        </li>
    </ul>
    <div class="d-grid gap-3">
        {% include 'producto/index_back.html' %}
    </div>

{% endblock content_producto %}

project/producto/templates/producto/prodcateg_form.html
{% extends 'producto/index.html' %}


{% block title %} Categorías de Productos {% endblock title %}

{% block content_producto %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="d-grid gap-3">
            <button type="submi" class="btn btn-success">Guardar</button>
            {% include 'producto/index_back.html' %}
        </div>
    </form>


{% endblock content_producto %}

project/producto/templates/producto/prodcateg_list.html
{% extends 'producto/index.html' %}


{% block title %} Lista de Categorías de Productos {% endblock title %}

{% block content_producto %}


    {% if object_list %}

        <!-- Sirve para buscar categorías por nombre. Se pasa a la variable consulta de la vista. -->
        <div class="py-lg-4">
            <form action="{% url 'producto:productocategoria_list' %}" method="get">
                <input name="consulta" type="text" placeholder="Buscar...">
            </form>
        </div>

        {% for categoria in object_list %}
            <ul>
                <li>{{ categoria.nombre }}
                    <a href="{% url 'producto:productocategoria_detail' categoria.id %}" class="btn btn-secondary">Ver detalle</a>
                    <a href="{% url 'producto:productocategoria_update' categoria.id %}" class="btn btn-primary">Actualizar</a>
                    <a href="{% url 'producto:productocategoria_delete' categoria.id %}" class="btn btn-danger">Eliminar</a>
                </li>
            </ul>
        {% endfor %}
    {% else %}
        <p class="fs-4 fst-italic">No hay registros ingresados</p>
    {% endif %}
    <div class="d-grid gap-3">
        {% include 'producto/index_back.html' with hola="Coder" %}
    </div>

{% endblock content_producto %}

project/producto/templates/producto/producto_confirm_delete.html
% extends 'producto/index.html' %}


{% block title %} Eliminación de Productos {% endblock title %}

{% block content_producto %}

    <p class="fs-5 fst-italic">¿Confirmas eliminar "{{ object }}"?</p>

    <form method="post">
        {% csrf_token %}
        <div class="d-grid gap-3">
            <button type="submit" class="btn btn-danger">Confirmar</button>
            {% include 'producto/index_back.html' %}
        </div>
    </form>

{% endblock content_producto %}

project/producto/templates/producto/producto_detail.html
{% extends 'producto/index.html' %}


{% block title %} Detalle de Productos {% endblock title %}

{% block content_producto %}

    <ul>
        <li>
            <p><strong>Categoría:</strong> {{ object.categoria }}</p>
            <p><strong>Nombre:</strong> {{ object.nombre }}</p>
            <p><strong>Unidad de medida:</strong> {{ object.unidad_de_medida }}</p>
            <p><strong>Cantidad:</strong> {{ object.cantidad }}</p>
            <p><strong>Precio:</strong> {{ object.precio }}</p>
            <p><strong>Descripción:</strong> {{ object.descripcion }}</p>
            <p><strong>Fecha de actualización:</strong> {{ object.fecha_actualizacion }}</p>
        </li>
    </ul>
    <div class="d-grid gap-3">
        {% include 'producto/index_back.html' %}
    </div>

{% endblock content_producto %}

project/producto/templates/producto/producto_form.html
{% extends 'producto/index.html' %}


{% block title %} Productos {% endblock title %}

{% block content_producto %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="d-grid gap-3">
            <button type="submi" class="btn btn-success">Guardar</button>
            {% include 'producto/index_back.html' %}
        </div>
    </form>


{% endblock content_producto %}

project/producto/templates/producto/producto_list.html
{% extends 'producto/index.html' %}


{% block title %} Lista de Productos {% endblock title %}

{% block content_producto %}


    {% if object_list %}

        {% for producto in object_list %}
            <ul>
                <li>{{ producto.nombre }} ${{ producto.precio }}
                    <a href="{% url 'producto:producto_detail' producto.id %}" class="btn btn-secondary">Ver detalle</a>
                    <a href="{% url 'producto:producto_update' producto.id %}" class="btn btn-primary">Actualizar</a>
                    <a href="{% url 'producto:producto_delete' producto.id %}" class="btn btn-danger">Eliminar</a>
                </li>
            </ul>
        {% endfor %}
    {% else %}
        <p class="fs-4 fst-italic">No hay registros ingresados</p>
    {% endif %}
    <div class="d-grid gap-3">
        {% include 'producto/index_back.html' %}
    </div>

{% endblock content_producto %}

project/producto/templates/productos/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

project/templates/index.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1> VENTA DE VINOS </h1>
    <a href="{% url 'cliente:index' %}">Ir a Clientes</a>
    <a href="{% url 'producto:index' %}">Ir a Productos</a>
    </body>
</html>